"""add_class_section_and_join_code

Revision ID: 2061d750672f
Revises: 544b8c7179b1
Create Date: 2026-06-12 15:43:03.465604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2061d750672f'
down_revision: Union[str, Sequence[str], None] = '544b8c7179b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('join_code', sa.String(length=6), nullable=True))
    op.create_index(op.f('ix_groups_join_code'), 'groups', ['join_code'], unique=True)
    op.add_column('user_profiles', sa.Column('class_section', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'class_section')
    op.drop_index(op.f('ix_groups_join_code'), table_name='groups')
    op.drop_column('groups', 'join_code')
    # ### end Alembic commands ###
