"""Add terminal_output and plots to saved_programs

Revision ID: 544b8c7179b1
Revises: 5c3828ebac64
Create Date: 2026-06-11 18:01:56.380033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544b8c7179b1'
down_revision: Union[str, Sequence[str], None] = '5c3828ebac64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_programs', sa.Column('terminal_output', sa.Text(), nullable=True))
    op.add_column('saved_programs', sa.Column('plots', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_programs', 'plots')
    op.drop_column('saved_programs', 'terminal_output')
    # ### end Alembic commands ###
