"""Add lesson_id to saved_programs

Revision ID: 5c3828ebac64
Revises: 92ce74c3ea97
Create Date: 2026-06-09 12:54:53.344841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3828ebac64'
down_revision: Union[str, Sequence[str], None] = '92ce74c3ea97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_programs', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'saved_programs', 'lessons', ['lesson_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_programs', type_='foreignkey')
    op.drop_column('saved_programs', 'lesson_id')
    # ### end Alembic commands ###
