import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../providers/creator_courses_provider.dart';
import '../../../../core/widgets/loading_overlay.dart';

class CurriculumBuilderScreen extends ConsumerStatefulWidget {
  const CurriculumBuilderScreen({super.key});

  @override
  ConsumerState<CurriculumBuilderScreen> createState() => _CurriculumBuilderScreenState();
}

class _CurriculumBuilderScreenState extends ConsumerState<CurriculumBuilderScreen> {
  int _step = 0;
  
  // IDs to keep track of the created hierarchy
  int? _courseId;
  int? _moduleId;
  int? _chapterId;
  
  // Controllers
  final _courseTitleCtrl = TextEditingController();
  final _courseDescCtrl = TextEditingController();
  String _difficulty = 'beginner';
  
  final _moduleTitleCtrl = TextEditingController();
  final _moduleDescCtrl = TextEditingController();
  
  final _chapterTitleCtrl = TextEditingController();
  final _chapterDescCtrl = TextEditingController();

  final _lessonTitleCtrl = TextEditingController();
  String _lessonType = 'video';
  final _lessonVideoUrlCtrl = TextEditingController();
  final _lessonContentCtrl = TextEditingController();

  Future<void> _createCourse() async {
    if (_courseTitleCtrl.text.isEmpty) return;
    final id = await ref.read(creatorCoursesProvider.notifier).createCourse(
      _courseTitleCtrl.text,
      _courseDescCtrl.text,
      _difficulty,
    );
    if (id != null) {
      setState(() {
        _courseId = id;
        _step = 1;
      });
    }
  }

  Future<void> _createModule() async {
    if (_moduleTitleCtrl.text.isEmpty || _courseId == null) return;
    final id = await ref.read(creatorCoursesProvider.notifier).createModule(
      _courseId!,
      _moduleTitleCtrl.text,
      _moduleDescCtrl.text,
    );
    if (id != null) {
      setState(() {
        _moduleId = id;
        _step = 2;
      });
    }
  }

  Future<void> _createChapter() async {
    if (_chapterTitleCtrl.text.isEmpty || _moduleId == null) return;
    final id = await ref.read(creatorCoursesProvider.notifier).createChapter(
      _moduleId!,
      _chapterTitleCtrl.text,
      _chapterDescCtrl.text,
    );
    if (id != null) {
      setState(() {
        _chapterId = id;
        _step = 3;
      });
    }
  }

  Future<void> _createLesson() async {
    if (_lessonTitleCtrl.text.isEmpty || _chapterId == null) return;
    
    Map<String, dynamic> body = {};
    if (_lessonType == 'video') {
      body['text'] = _lessonContentCtrl.text;
    } else if (_lessonType == 'text') {
      body['text'] = _lessonContentCtrl.text;
    }

    final id = await ref.read(creatorCoursesProvider.notifier).createLesson(
      _chapterId!,
      _lessonTitleCtrl.text,
      _lessonType == 'quiz' ? 'quiz' : _lessonType,
      body,
    );

    if (id != null) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Lesson Created successfully!')),
      );
      if (_lessonType == 'quiz') {
        context.push('/creator/quiz_builder/$id');
      } else {
        context.pop(); // Go back to dashboard
      }
    }
  }

  // AI Settings
  final _aiPromptCtrl = TextEditingController();
  String _aiModel = 'Google Gemini';
  List<dynamic> _generatedModules = [];

  Future<void> _generateCourseWithAI() async {
    if (_aiPromptCtrl.text.isEmpty) return;
    final data = await ref.read(creatorCoursesProvider.notifier).generateCourseWithAI(
      _aiPromptCtrl.text,
      _aiModel,
    );
    if (data != null && data['modules'] != null) {
      setState(() {
        _generatedModules = data['modules'];
        // Pre-fill the course title and description based on the prompt
        _courseTitleCtrl.text = "${_aiPromptCtrl.text} Course";
        _courseDescCtrl.text = "Generated by $_aiModel";
      });
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Generated ${_generatedModules.length} modules! Continue in the stepper to finalize.')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final state = ref.watch(creatorCoursesProvider);
    final isLoading = state.isLoading;

    return LoadingOverlay(
      isLoading: isLoading,
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Curriculum Builder'),
        ),
        body: Column(
        children: [
          ExpansionTile(
            leading: const Icon(Icons.auto_awesome, color: Colors.purple),
            title: const Text('AI Course Generator', style: TextStyle(fontWeight: FontWeight.bold, color: Colors.purple)),
            subtitle: const Text('Generate curriculum structure instantly'),
            children: [
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: Column(
                  children: [
                    TextField(
                      controller: _aiPromptCtrl,
                      decoration: const InputDecoration(
                        labelText: 'Topic / Prompt',
                        hintText: 'e.g. Advanced Data Science in Python',
                        border: OutlineInputBorder(),
                      ),
                      maxLines: 2,
                    ),
                    const SizedBox(height: 16),
                    Row(
                      children: [
                        Expanded(
                          child: DropdownButtonFormField<String>(
                            value: _aiModel,
                            decoration: const InputDecoration(
                              labelText: 'AI Model',
                              border: OutlineInputBorder(),
                            ),
                            items: const [
                              DropdownMenuItem(value: 'Google Gemini', child: Text('Google Gemini')),
                              DropdownMenuItem(value: 'Llama 3', child: Text('Llama 3')),
                            ],
                            onChanged: (val) => setState(() => _aiModel = val!),
                          ),
                        ),
                        const SizedBox(width: 16),
                        ElevatedButton.icon(
                          onPressed: isLoading ? null : _generateCourseWithAI,
                          icon: const Icon(Icons.flash_on),
                          label: const Text('Generate'),
                          style: ElevatedButton.styleFrom(
                            backgroundColor: Colors.purple,
                            foregroundColor: Colors.white,
                            padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 24),
                          ),
                        ),
                      ],
                    ),
                    if (_generatedModules.isNotEmpty) ...[
                      const SizedBox(height: 16),
                      Container(
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          color: Colors.green.withOpacity(0.1),
                          borderRadius: BorderRadius.circular(8),
                          border: Border.all(color: Colors.green),
                        ),
                        child: Text(
                          'Success! We generated ${_generatedModules.length} modules. You can now tweak the course title below and hit Continue.',
                          style: const TextStyle(color: Colors.green, fontWeight: FontWeight.bold),
                        ),
                      ),
                    ]
                  ],
                ),
              ),
            ],
          ),
          Expanded(
            child: Stepper(
              type: StepperType.vertical,
              physics: const ClampingScrollPhysics(),
              currentStep: _step,
              onStepContinue: () {
                if (_step == 0) _createCourse();
                else if (_step == 1) _createModule();
                else if (_step == 2) _createChapter();
                else if (_step == 3) _createLesson();
              },
              onStepCancel: () {
                if (_step > 0) {
                  setState(() => _step -= 1);
                }
              },
              steps: [
                Step(
                  title: const Text('Create Course'),
                  isActive: _step >= 0,
                  content: Column(
                    children: [
                      if (_generatedModules.isNotEmpty)
                        Container(
                          padding: const EdgeInsets.all(12),
                          margin: const EdgeInsets.only(bottom: 16),
                          decoration: BoxDecoration(
                            color: Colors.green.withOpacity(0.1),
                            borderRadius: BorderRadius.circular(8),
                            border: Border.all(color: Colors.green.withOpacity(0.3)),
                          ),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              const Text('AI Generated Curriculum Preview:', style: TextStyle(fontWeight: FontWeight.bold, color: Colors.green)),
                              const SizedBox(height: 8),
                              ..._generatedModules.map((m) => Padding(
                                padding: const EdgeInsets.only(bottom: 4),
                                child: Text('• ${m['title']}', style: const TextStyle(fontSize: 13)),
                              )),
                              const SizedBox(height: 8),
                              const Text('Complete the steps below to save your course.', style: TextStyle(fontSize: 12, fontStyle: FontStyle.italic)),
                            ],
                          ),
                        ),
                      TextField(
                        controller: _courseTitleCtrl,
                        decoration: const InputDecoration(labelText: 'Course Title'),
                      ),
                      const SizedBox(height: 16),
                      TextField(
                        controller: _courseDescCtrl,
                        decoration: const InputDecoration(labelText: 'Description'),
                        maxLines: 3,
                      ),
                      const SizedBox(height: 16),
                      DropdownButtonFormField<String>(
                        value: _difficulty,
                        decoration: const InputDecoration(labelText: 'Difficulty'),
                        items: const [
                          DropdownMenuItem(value: 'beginner', child: Text('Beginner')),
                          DropdownMenuItem(value: 'intermediate', child: Text('Intermediate')),
                          DropdownMenuItem(value: 'advanced', child: Text('Advanced')),
                        ],
                        onChanged: (v) => setState(() => _difficulty = v!),
                      ),
                    ],
                  ),
                ),
                Step(
                  title: const Text('Add Module'),
                  isActive: _step >= 1,
                  content: Column(
                    children: [
                      TextField(
                        controller: _moduleTitleCtrl,
                        decoration: const InputDecoration(labelText: 'Module Title'),
                      ),
                      const SizedBox(height: 16),
                      TextField(
                        controller: _moduleDescCtrl,
                        decoration: const InputDecoration(labelText: 'Description'),
                        maxLines: 2,
                      ),
                    ],
                  ),
                ),
                Step(
                  title: const Text('Add Chapter'),
                  isActive: _step >= 2,
                  content: Column(
                    children: [
                      TextField(
                        controller: _chapterTitleCtrl,
                        decoration: const InputDecoration(labelText: 'Chapter Title'),
                      ),
                      const SizedBox(height: 16),
                      TextField(
                        controller: _chapterDescCtrl,
                        decoration: const InputDecoration(labelText: 'Description'),
                        maxLines: 2,
                      ),
                    ],
                  ),
                ),
                Step(
                  title: const Text('Add Lesson'),
                  isActive: _step >= 3,
                  content: Column(
                    children: [
                      TextField(
                        controller: _lessonTitleCtrl,
                        decoration: const InputDecoration(labelText: 'Lesson Title'),
                      ),
                      const SizedBox(height: 16),
                      DropdownButtonFormField<String>(
                        value: _lessonType,
                        decoration: const InputDecoration(labelText: 'Content Type'),
                        items: const [
                          DropdownMenuItem(value: 'video', child: Text('Video Lesson')),
                          DropdownMenuItem(value: 'text', child: Text('Text/Article')),
                          DropdownMenuItem(value: 'quiz', child: Text('Interactive Quiz')),
                          DropdownMenuItem(value: 'code_challenge', child: Text('Code Challenge')),
                        ],
                        onChanged: (v) => setState(() => _lessonType = v!),
                      ),
                      const SizedBox(height: 16),
                      if (_lessonType == 'video') ...[
                        TextField(
                          controller: _lessonContentCtrl,
                          decoration: const InputDecoration(labelText: 'Video Description / Summary'),
                          maxLines: 3,
                        ),
                      ] else if (_lessonType == 'text') ...[
                        TextField(
                          controller: _lessonContentCtrl,
                          decoration: const InputDecoration(labelText: 'Article Content (Markdown)'),
                          maxLines: 6,
                        ),
                      ] else ...[
                        const Text('You will be redirected to the specific builder for this content type after saving the lesson structure.'),
                      ],
                    ],
                  ),
                ),
              ],
            ),
          ), // closes Expanded
        ], // closes Column children
      ), // closes Column
      ), // closes Scaffold
    ); // closes LoadingOverlay
  }
}
